# Book settings
# -------------
title: Toiminnallisuustestausta
author: LUMA-team, Lapland UAS / Jyri Kivinen
copyright: "2022"
logo: images/logo.png

# Execution settings
# -------------------
execute:
  execute_notebooks: cache

# GitHub-settings
# ----------------
repository:
  url: https://github.com/luma-lapinamk/jyri-test
  branch: main

# HTML-settings and launch buttons
# ---------------------------------
html:
  use_issues_button: false
  use_repository_button: true
launch_buttons:
  colab_url: "https://colab.research.google.com"
  binderhub_url: "https://mybinder.org"
  thebe: true
